local M = {}

--- @param colors PalenightColors
function M.generate(colors)
  return {
    ['@annotation'] = { fg = colors.yellow },
    ['@attribute'] = { fg = colors.light_red },
    ['@boolean'] = { fg = colors.red, italic = true },
    ['@character'] = { fg = colors.green },
    ['@character.special'] = { fg = colors.dark_purple },
    ['@comment'] = { fg = colors.comment_grey },
    ['@conditional'] = { fg = colors.purple },
    ['@constant.builtin'] = { fg = colors.orange },
    ['@constant'] = { fg = colors.cyan },
    ['@constant.macro'] = { fg = colors.dark_orange },
    ['@constructor'] = { fg = colors.white },
    ['@define'] = { fg = colors.purple },
    ['@exception'] = { fg = colors.purple },
    ['@field'] = { fg = colors.cyan },
    ['@float'] = { fg = colors.dark_yellow },
    ['@function.builtin'] = { fg = colors.cyan },
    ['@function.call'] = { fg = colors.light_blue },
    ['@function'] = { fg = colors.light_blue },
    ['@function.macro'] = { fg = colors.purple, italic = true },
    ['@include'] = { fg = colors.blue },
    ['@keyword'] = { fg = colors.red, italic = true },
    ['@keyword.function'] = { fg = colors.red, italic = true },
    ['@keyword.operator'] = { fg = colors.dark_purple },
    ['@keyword.return'] = { fg = colors.red },
    ['@label'] = { fg = colors.purple },
    ['@method.builtin'] = { fg = colors.cyan },
    ['@method.call'] = { fg = colors.blue },
    ['@method'] = { fg = colors.blue },
    ['@namespace'] = { fg = colors.dark_purple },
    ['@number'] = { fg = colors.orange },
    ['@operator'] = { fg = colors.white },
    ['@parameter.builtin'] = { fg = colors.cyan },
    ['@parameter'] = { fg = colors.white, italic = true },
    ['@parameter.reference'] = { fg = colors.menu_grey },
    ['@property'] = { fg = colors.red },
    ['@punctuation.bracket'] = { fg = colors.white },
    ['@punctuation.delimiter'] = { fg = colors.white },
    ['@punctuation'] = { fg = colors.white },
    ['@punctuation.special'] = { fg = colors.white },
    ['@repeat'] = { fg = colors.purple },
    ['@storageclass'] = { fg = colors.yellow, italic = true },
    ['@string.escape'] = { fg = colors.comment_grey },
    ['@string'] = { fg = colors.light_green },
    ['@string.regex'] = { fg = colors.dark_green },
    ['@string.special'] = { fg = colors.yellow },
    ['@symbol'] = { fg = colors.red },
    ['@tag.attribute'] = { fg = colors.dark_purple },
    ['@tag.delimiter'] = { fg = colors.white },
    ['@tag'] = { fg = colors.light_red },
    ['@type.builtin'] = { fg = colors.dark_orange },
    ['@type'] = { fg = colors.light_orange },
    ['@type.qualifier'] = { fg = colors.orange },
    ['@variable.builtin'] = { fg = colors.dark_yellow },
    ['@variable'] = { fg = colors.white },
  }
end

return M
